import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import HomeWrapper from '../src/StyledComponents/HomeWrapper'
import Navigation from '../src/Components/Navigation'
import Landing from '../src/Components/Landing'
import Gateway from '../src/Components/Gateway'
import Companies from '../src/Components/Companies'
import About from '../src/Components/About'
import Contact from '../src/Components/Contact'


export default function Home({ data }) {  


  return (
    <HomeWrapper className='home' >
      <Head>
        <title> NAGCOM </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Landing />
      <About/>
      <Companies data={data} />
      <Gateway /> 
      <Contact />


    </HomeWrapper>
  )
}

export async function getStaticProps() {
  const response = await fetch('http://localhost:3000/api/companies')
  const data = await response.json()
  return {
      props: {
          data
      }
  }
}
