import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import HomeWrapper from '../src/StyledComponents/HomeWrapper'
import Navigation from '../src/Components/Navigation'
import Landing from '../src/Components/Landing'
import Gateway from '../src/Components/Gateway'
import Companies from '../src/Components/Companies'
import About from '../src/Components/About'
import Contact from '../src/Components/Contact'


export default function Home() {  


  return (
    <HomeWrapper className='home' >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />

      <Landing />
      <Gateway /> 
      <Companies />
      <About/>
      <Contact />


    </HomeWrapper>
  )
}
