import Head from 'next/head'
import HomeWrapper from '../src/StyledComponents/HomeWrapper'
import Landing from '../src/Components/Landing'
import Gateway from '../src/Components/Gateway'
import Companies from '../src/Components/Companies'
import About from '../src/Components/About'
import Contact from '../src/Components/Contact'
import companyDetails from '../src/assets/companiesDetails'


export default function Home({ data }) {  


  return (
    <HomeWrapper className='home' >
      <Head>
        <title> NAGCOM </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Landing />
      <About/>
      <Companies data={companyDetails} />
      <Gateway /> 
      <Contact />


    </HomeWrapper>
  )
}

